### ISSUE TITLE
Cannot create migration with AshPostgres

### ISSUE THREAD

**Issue by scflode** [ash-project/ash_paper_trail#1]
The following error occurs when trying to run `mix ash_postgres.generate_migrations --name add_paper_trail_to_ticket`.

```
** (ArgumentError) No such entity nil found.

    nil.spark_dsl_config()
    (spark 0.3.7) lib/spark/dsl/extension.ex:129: Spark.Dsl.Extension.dsl!/1
    (spark 0.3.7) lib/spark/dsl/extension.ex:147: Spark.Dsl.Extension.get_entities/2
    (ash 2.5.8) lib/ash/resource/info.ex:564: Ash.Resource.Info.attribute/2
    (ash_postgres 1.3.3) lib/migration_generator/migration_generator.ex:2135: anonymous fn/4 in AshPostgres.MigrationGenerator.find_reference/3
    (elixir 1.14.3) lib/enum.ex:4239: Enum.find_value_list/3
    (ash_postgres 1.3.3) lib/migration_generator/migration_generator.ex:2125: anonymous fn/3 in AshPostgres.MigrationGenerator.attributes/2
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
```

You can see the setup here:
https://github.com/scflode/ash_playground/pull/3

**Comment by zachdaniel** [comment]
Somehow I completely missed this :(

Its been open for a long time, I'll close it for now, will reopen if you or someone else confirms the issue remains.
