### ISSUE TITLE
KeyError after upgrading to 0.3.1

### ISSUE THREAD

**Issue by sbennett33** [ash-project/ash_paper_trail#139]
**Describe the bug**
Issue upgrading to `0.3.1`.

Getting the following error after upgrading from `0.3.0` to `0.3.1`
```
** (EXIT from #PID<0.67704.0>) an exception was raised:
         ** (Ash.Error.Unknown)
     Bread Crumbs:
       > Exception raised in bulk update: Level.Resources.User.update
       > Exception raised in: Level.Resources.User.update
       > Exception raised in: Level.Resources.GroupMember.create

     Unknown Error

     * ** (KeyError) key :changed? not found in: %{
       private: %{actor: nil, authorize?: true, pre_flight_authorization?: false},
       data_layer: %{use_atomic_update_data?: true}
     }
       (ash_paper_trail 0.3.1) lib/resource/changes/create_new_version.ex:76: anonymous fn/1 in AshPaperTrail.Resource.Changes.CreateNewVersion.bulk_build_notifications/1
       (elixir 1.18.0) lib/enum.ex:4386: Enum.filter_list/2
       (ash_paper_trail 0.3.1) lib/resource/changes/create_new_version.ex:73: AshPaperTrail.Resource.Changes.CreateNewVersion.bulk_build_notifications/1
       (ash_paper_trail 0.3.1) lib/resource/changes/create_new_version.ex:39: AshPaperTrail.Resource.Changes.CreateNewVersion.after_batch/3
       (ash 3.4.48) lib/ash/actions/update/bulk.ex:930: anonymous fn/6 in Ash.Actions.Update.Bulk.run_atomic_after_batch_hooks/5
       (elixir 1.18.0) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ash 3.4.48) lib/ash/actions/update/bulk.ex:923: anonymous fn/5 in Ash.Actions.Update.Bulk.run_atomic_after_batch_hooks/5
       (stdlib 6.2) maps.erl:860: :maps.fold_1/4
       (ash 3.4.48) lib/ash/actions/update/bulk.ex:902: Ash.Actions.Update.Bulk.run_atomic_after_batch_hooks/5
       (ash 3.4.48) lib/ash/actions/update/bulk.ex:604: Ash.Actions.Update.Bulk.do_atomic_update/5
       (ash 3.4.48) lib/ash/data_layer/data_layer.ex:432: Ash.DataLayer.transaction/4
       (ash 3.4.48) lib/ash/actions/update/bulk.ex:255: Ash.Actions.Update.Bulk.run/6
       (ash 3.4.48) lib/ash/actions/update/update.ex:158: Ash.Actions.Update.run/4
       (ash 3.4.48) lib/ash.ex:2641: Ash.update/3
       (level 0.1.0) lib/level/resources/group_member/changes/set_active_member.ex:30: anonymous fn/2 in Level.Resources.GroupMember.Changes.SetActiveMember.change/3
       (ash 3.4.48) lib/ash/changeset/changeset.ex:4017: anonymous fn/2 in Ash.Changeset.run_after_actions/3
       (elixir 1.18.0) lib/enum.ex:4964: Enumerable.List.reduce/3
       (elixir 1.18.0) lib/enum.ex:2600: Enum.reduce_while/3
       (ash 3.4.48) lib/ash/changeset/changeset.ex:3492: anonymous fn/3 in Ash.Changeset.with_hooks/3
       (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1400: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
             (ash_paper_trail 0.3.1) lib/resource/changes/create_new_version.ex:76: anonymous fn/1 in AshPaperTrail.Resource.Changes.CreateNewVersion.bulk_build_notifications/1
             (elixir 1.18.0) lib/enum.ex:4386: Enum.filter_list/2
             (ash_paper_trail 0.3.1) lib/resource/changes/create_new_version.ex:73: AshPaperTrail.Resource.Changes.CreateNewVersion.bulk_build_notifications/1
             (ash_paper_trail 0.3.1) lib/resource/changes/create_new_version.ex:39: AshPaperTrail.Resource.Changes.CreateNewVersion.after_batch/3
             (ash 3.4.48) lib/ash/actions/update/bulk.ex:930: anonymous fn/6 in Ash.Actions.Update.Bulk.run_atomic_after_batch_hooks/5
             (elixir 1.18.0) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
             (ash 3.4.48) lib/ash/actions/update/bulk.ex:923: anonymous fn/5 in Ash.Actions.Update.Bulk.run_atomic_after_batch_hooks/5
             (stdlib 6.2) maps.erl:860: :maps.fold_1/4
             (ash 3.4.48) lib/ash/actions/update/bulk.ex:902: Ash.Actions.Update.Bulk.run_atomic_after_batch_hooks/5
             (ash 3.4.48) lib/ash/actions/update/bulk.ex:604: Ash.Actions.Update.Bulk.do_atomic_update/5
             (ash 3.4.48) lib/ash/data_layer/data_layer.ex:432: Ash.DataLayer.transaction/4
             (ash 3.4.48) lib/ash/actions/update/bulk.ex:255: Ash.Actions.Update.Bulk.run/6
             (ash 3.4.48) lib/ash/actions/update/update.ex:158: Ash.Actions.Update.run/4
             (ash 3.4.48) lib/ash.ex:2641: Ash.update/3
             (level 0.1.0) lib/level/resources/group_member/changes/set_active_member.ex:30: anonymous fn/2 in Level.Resources.GroupMember.Changes.SetActiveMember.change/3
             (ash 3.4.48) lib/ash/changeset/changeset.ex:4017: anonymous fn/2 in Ash.Changeset.run_after_actions/3
             (elixir 1.18.0) lib/enum.ex:4964: Enumerable.List.reduce/3
             (elixir 1.18.0) lib/enum.ex:2600: Enum.reduce_while/3
             (ash 3.4.48) lib/ash/changeset/changeset.ex:3492: anonymous fn/3 in Ash.Changeset.with_hooks/3
             (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1400: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
```

**To Reproduce**
We have AshPaperTrail set up to track our `User` resource. We're attempting to update an instance of the `User` resource inside an `after_action` callback in a custom `Ash.Resource.Change`.

**Expected behavior**
Don't do that?

**Runtime**
 - Elixir version: 1.17.2
 - Erlang version: 27.0.1
 - OS: MacOS
 - Ash version: 3.4.48
 - any related extension versions

**Comment by sbennett33** [comment]
For context here's the change function we're running:
```elixir
  @impl Change
  def change(changeset, _opts, _context) do
    Ash.Changeset.after_action(
      changeset,
      fn %{
           attributes: %{
             user_id: user_id
           }
         },
         %GroupMember{id: id} = result ->
        {:ok, user} = Ash.get(User, user_id)

        case user do
          %User{active_member_id: nil} ->
            Logger.info("Setting active member id for user #{user.id}")

            User.update(user, %{active_member_id: id})

          %User{active_member_id: _} ->
            Logger.info("Active member already set for user #{user.id}, skipping")
        end

        {:ok, result}
      end
    )
  end
```

**Comment by serpent213** [comment]
Probably related issue here:

```
     ** (Ash.Error.Unknown)
     Bread Crumbs:
       > Exception raised in: Heimdall.Members.Member.create

     Unknown Error

     * ** (Protocol.UndefinedError) protocol Enumerable not implemented for ~D[1996-04-18] of type Date (a struct). This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Iter, Jason.OrderedObject, List, Map, MapSet, Phoenix.LiveView.LiveStream, Postgrex.Stream, Range, Rewrite, Stream, StreamData, Timex.Interval
       (elixir 1.17.3) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir 1.17.3) lib/enum.ex:166: Enumerable.reduce/3
       (elixir 1.17.3) lib/enum.ex:4423: Enum.map/2
       (ash_paper_trail 0.3.1) lib/resource/changes/create_new_version.ex:243: AshPaperTrail.Resource.Changes.CreateNewVersion.extract_casted_params_values/2
       (ash_paper_trail 0.3.1) lib/resource/changes/create_new_version.ex:184: anonymous fn/3 in AshPaperTrail.Resource.Changes.CreateNewVersion.build_notifications/3
```

...running just a plain *create*.

I bisected it down to https://github.com/ash-project/ash_paper_trail/commit/03ee06f08d574183f3085ecf4e5e135f67298914.

**Comment by nallwhy** [comment]
We got this error with 0.3.1.

```
** (Ash.Error.Unknown) 
Bread Crumbs:
  > Exception raised in bulk create: Azir.Resources.Setting.create

Unknown Error

* ** (FunctionClauseError) no function clause matching in AshPaperTrail.Resource.Changes.CreateNewVersion.after_batch/3
  (ash_paper_trail 0.3.1) AshPaperTrail.Resource.Changes.CreateNewVersion.after_batch([], [], %Ash.Resource.Change.Context{actor: nil, tenant: nil, authorize?: true, tracer: [AshAppsignal], bulk?: true})
  (ash 3.4.48) lib/ash/actions/create/bulk.ex:1553: anonymous fn/8 in Ash.Actions.Create.Bulk.run_bulk_after_changes/8
  (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ash 3.4.48) lib/ash/actions/create/bulk.ex:1443: Ash.Actions.Create.Bulk.process_results/11
  (ash 3.4.48) lib/ash/actions/create/bulk.ex:625: Ash.Actions.Create.Bulk.do_handle_batch/13
  (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1400: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
  (db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4
  (ash 3.4.48) lib/ash/actions/create/bulk.ex:509: Ash.Actions.Create.Bulk.handle_batch/10
  (ash 3.4.48) lib/ash/actions/create/bulk.ex:180: anonymous fn/13 in Ash.Actions.Create.Bulk.do_run/5
  (elixir 1.17.3) lib/stream.ex:613: anonymous fn/4 in Stream.map/2
  (elixir 1.17.3) lib/stream.ex:1879: anonymous fn/3 in Enumerable.Stream.reduce/3
  (elixir 1.17.3) lib/stream.ex:289: Stream.after_chunk_while/2
  (elixir 1.17.3) lib/stream.ex:1908: Enumerable.Stream.do_done/2
  (elixir 1.17.3) lib/stream.ex:1891: Enumerable.Stream.do_each/4
  (elixir 1.17.3) lib/stream.ex:690: Stream.run/1
  (ash 3.4.48) lib/ash/actions/create/bulk.ex:207: Ash.Actions.Create.Bulk.do_run/5
  (ash 3.4.48) lib/ash/actions/create/bulk.ex:83: Ash.Actions.Create.Bulk.run/5
  (ash 3.4.48) lib/ash.ex:2222: Ash.bulk_create!/4
```

**Comment by zachdaniel** [comment]
Can you please try `main` of `ash` and `ash_paper_trail`? Thanks

**Comment by lardcanoe** [comment]
Success. My tests passed.

```
      {:ash, git: "https://github.com/ash-project/ash.git", override: true},
      {:ash_paper_trail, github: "ash-project/ash_paper_trail", override: true},
```

```
  "ash": {:git, "https://github.com/ash-project/ash.git", "f847a4b653571352a15e6802df880c95faaf49c5", []},
  "ash_paper_trail": {:git, "https://github.com/ash-project/ash_paper_trail.git", "865aa2eac6551edf8e3d39458e2cb56140913ee4", []},
```

**Comment by zachdaniel** [comment]
🥳 They will be released this week or next week then
