### ISSUE TITLE
Error on migration

### ISSUE THREAD

**Issue by djacobs7** [ash-project/ash_paper_trail#5]
Thanks for your help with everything so far.  

I downloaded the latest patch and now I am getting this error. I have version 1.1.26 of spark according to my mix.lock file.  

[nix-shell:~/git/api]$  mix ash_postgres.generate_migrations --name add_versions

== Compilation error in file lib/myapp/myapi/resources/section.ex ==
** (NimbleOptions.ValidationError) unknown options [:source], valid options are: [:manual, :no_attributes?, :name, :destination, :description, :destination_attribute, :validate_destination_attribute?, :source_attribute, :relationship_context, :private?, :not_found_message, :writable?, :read_action, :api, :filter, :filterable?, :sort, :could_be_related_at_creation?, :violation_message]
    (spark 1.1.26) lib/spark/dsl/extension.ex:737: Spark.Dsl.Extension.raise_transformer_error/2
    (elixir 1.15.4) lib/enum.ex:4830: Enumerable.List.reduce/3
    (elixir 1.15.4) lib/enum.ex:2564: Enum.reduce_while/3
    /Users/danieljacobs/git/api/lib/scribble/scribe/resources/section.ex:20: (file)
    (stdlib 4.3.1.2) erl_eval.erl:748: :erl_eval.do_apply/7
    (stdlib 4.3.1.2) erl_eval.erl:961: :erl_eval.expr_list/7
    (stdlib 4.3.1.2) erl_eval.erl:454: :erl_eval.expr/6

**Comment by zachdaniel** [comment]
Sorry, mistake on my part. Try again :)

**Comment by djacobs7** [comment]
Nice! Looks good now.  Really appreciate the help!

[nix-shell:~/git/api]$  mix ash_postgres.generate_migrations --name
add_versions

Generating Migrations:
* creating priv/repo/migrations/20230913163625_add_versions.exs
